Repository Laboratoria/curriculum, pull requests merged in 2018-09, with the labels that each got.

#705 V2.x Niveles habilidades blandas
  projects/04-social-network-frameworks/README.md
Labels: content

#712 content(projects/social-network-frameworks): quita requisitos de UX
  projects/04-social-network-frameworks/README.md
Labels: needs-review

#711 V2.x - Arreglando redacción sobre frameworks y librerias Social Network Framework
  projects/04-social-network-frameworks/README.md
Labels: needs-review

#715 proofread for pt-br translation of sprint 5 - spa
  06-spa/00-how-the-web-works/00-opening/README.md
  06-spa/00-how-the-web-works/02-components-of-the-web/README.md
  06-spa/00-how-the-web-works/03-html/README.md
  06-spa/00-how-the-web-works/05-http/README.md
  06-spa/01-html-5/00-opening/README.md
  06-spa/01-html-5/01-html-vs-html5/README.md
  06-spa/01-html-5/02-browser-apis/README.md
  06-spa/01-html-5/03-audio-video/README.md
  06-spa/01-html-5/04-media-challenges/README.md
  06-spa/01-html-5/05-web-storage/README.md
  06-spa/01-html-5/06-storage-challenges/README.md
  06-spa/01-html-5/07-geolocation/README.md
  06-spa/01-html-5/09-dnd/README.md
  06-spa/01-html-5/10-dnd-challenges/README.md
  06-spa/01-html-5/11-more-apis/README.md
  06-spa/02-async/00-opening/README.md
  06-spa/02-async/01-callbacks/README.md
  06-spa/02-async/02-events/README.md
  06-spa/02-async/03-bubbling-capturing/README.md
  06-spa/02-async/04-this-eventtarget/README.md
  06-spa/02-async/05-promises/README.md
  06-spa/03-asynchronous-js-request/01-client-server/README.md
  06-spa/03-asynchronous-js-request/02-ajax/README.md
  06-spa/03-asynchronous-js-request/03-apis/README.md
  06-spa/03-asynchronous-js-request/04-xhr/README.md
  06-spa/03-asynchronous-js-request/06-xhr-quiz/README.md
  06-spa/03-asynchronous-js-request/07-xhr-challenges/README.md
  06-spa/03-asynchronous-js-request/08-xhr-recap/README.md
  06-spa/03-asynchronous-js-request/09-jq-ajax/README.md
  06-spa/03-asynchronous-js-request/10-jq-ajax-demo/README.md
  06-spa/03-asynchronous-js-request/11-jq-shorthand-methods/README.md
  06-spa/03-asynchronous-js-request/14-jq-ajax-challenges/README.md
  06-spa/03-asynchronous-js-request/15-jq-ajax-recap/README.md
  06-spa/03-asynchronous-js-request/jq-source-code/README.md
  06-spa/05-working-with-apis/00-opening/README.md
  06-spa/05-working-with-apis/01-third-party-apis/README.md
  06-spa/05-working-with-apis/02-web-apis/README.md
  06-spa/05-working-with-apis/03-rest/README.md
  06-spa/05-working-with-apis/04-crud/README.md
  06-spa/05-working-with-apis/05-api-challenges/README.md
  06-spa/05-working-with-apis/06-quiz/README.md
  06-spa/06-mixing-up/01-challenge-1/README.md
  06-spa/06-mixing-up/02-challenge-2/README.md
  06-spa/06-mixing-up/03-challenge-3/README.md
  06-spa/06-mixing-up/04-challenge-4/README.md
  06-spa/06-mixing-up/05-challenge-5/README.md
  06-spa/06-mixing-up/06-challenge-6/README.md
  06-spa/06-mixing-up/08-challenge-8/README.md
  06-spa/06-mixing-up/09-challenge-9/README.md
  06-spa/07-final-product/00-opening/README.md
  06-spa/07-final-product/01-spa/README.md
  06-spa/07-final-product/02-build-your-own-spa/README.md
  06-spa/07-final-product/03-final-product/README.md
  06-spa/07-final-product/04-code-review/README.md
  06-spa/07-final-product/05-solution/README.md
  06-spa/07-final-product/06-retrospective/README.md
Labels: content, enhancement, translation

#716 Modify folder index
  05-deep-dive/03-foundations/11-practice/01-power-of-two/README.md
  05-deep-dive/03-foundations/11-practice/01-power-of-two/boilerplate/powerOfTwo.js
  05-deep-dive/03-foundations/11-practice/01-power-of-two/solution/powerOfTwo.js
  05-deep-dive/03-foundations/11-practice/01-power-of-two/test/powerOfTwo.spec.js
  05-deep-dive/03-foundations/11-practice/02-reverse/README.md
  05-deep-dive/03-foundations/11-practice/02-reverse/boilerplate/reverse.js
  05-deep-dive/03-foundations/11-practice/02-reverse/solution/reverse.js
  05-deep-dive/03-foundations/11-practice/02-reverse/test/reverse.spec.js
  05-deep-dive/03-foundations/11-practice/03-object-properties-counter/README.md
  05-deep-dive/03-foundations/11-practice/03-object-properties-counter/boilerplate/objectPropertiesCounter.js
  05-deep-dive/03-foundations/11-practice/03-object-properties-counter/solution/objectPropertiesCounter.js
  05-deep-dive/03-foundations/11-practice/03-object-properties-counter/test/objectPropertiesCounter.spec.js
  05-deep-dive/03-foundations/11-practice/04-currency-amount/README.md
  05-deep-dive/03-foundations/11-practice/04-currency-amount/boilerplate/currencyAmount.js
  05-deep-dive/03-foundations/11-practice/04-currency-amount/solution/currencyAmount.js
  05-deep-dive/03-foundations/11-practice/04-currency-amount/test/currencyAmount.spec.js
Labels: enhancement

#719 projects(burger-queen): switches focus to frameworks and PWA, with clear milestones
  projects/04-burger-queen/.editorconfig
  projects/04-burger-queen/README.md
  projects/04-burger-queen/firebase.json
  projects/04-burger-queen/firestore.indexes.json
  projects/04-burger-queen/firestore.rules
  projects/04-burger-queen/functions/.eslintrc.json
  projects/04-burger-queen/functions/index.js
  projects/04-burger-queen/functions/package.json
Labels: needs-review

#701 chore(projects): renames folders and updates info in main readme
  .mdlintignore
  README.md
  projects/000-FIXME/01-card-validation/README.md
  projects/000-FIXME/04-cardify/README.md
  projects/000-FIXME/04-mixing-up/00-opening/README.md
  projects/000-FIXME/04-mixing-up/01-challenge-1/README.md
  projects/000-FIXME/04-mixing-up/02-challenge-2/README.md
  projects/000-FIXME/04-mixing-up/03-challenge-3/README.md
  projects/000-FIXME/04-mixing-up/04-challenge-4/README.md
  projects/000-FIXME/04-mixing-up/05-challenge-5/README.md
  projects/000-FIXME/04-mixing-up/06-challenge-6/README.md
  projects/000-FIXME/04-mixing-up/07-challenge-7/README.md
  projects/000-FIXME/04-mixing-up/08-challenge-8/README.md
  projects/000-FIXME/04-mixing-up/09-challenge-9/README.md
  projects/000-FIXME/05-final-product/00-opening/README.md
  projects/000-FIXME/05-final-product/01-spa/README.md
  projects/000-FIXME/05-final-product/02-build-your-own-spa/README.md
  projects/000-FIXME/05-final-product/03-final-product/README.md
  projects/000-FIXME/xx-game-fp/02-workshop/00-opening/README.md
  projects/000-FIXME/xx-game-fp/02-workshop/01-refactoring/README.md
  projects/000-FIXME/xx-game-fp/02-workshop/02-closing/README.md
  projects/000-FIXME/xx-game-fp/04-workshop/00-opening/README.md
  projects/000-FIXME/xx-game-fp/04-workshop/01-refactoring/README.md
  projects/000-FIXME/xx-game-fp/04-workshop/02-closing/README.md
  projects/000-FIXME/xx-game-fp/06-workshop/00-opening/README.md
  projects/000-FIXME/xx-game-fp/06-workshop/01-refactoring/README.md
  projects/000-FIXME/xx-game-fp/06-workshop/02-closing/README.md
  projects/000-FIXME/xx-game-fp/07-demos/00-opening/README.md
  projects/000-FIXME/xx-game-fp/07-demos/01-demos/README.md
  projects/000-FIXME/xx-game-fp/07-demos/02-closing/README.md
  projects/000-FIXME/xx-game-fp/README.md
  projects/000-FIXME/xx-game/02-workshop/00-opening/README.md
  projects/000-FIXME/xx-game/02-workshop/01-git+github/README.md
  projects/000-FIXME/xx-game/02-workshop/02-teams/README.md
  projects/000-FIXME/xx-game/02-workshop/03-tasks/README.md
  projects/000-FIXME/xx-game/04-game-oop/01-hacking/README.md
  projects/000-FIXME/xx-game/05-hacking/01-hacking/README.md
  projects/000-FIXME/xx-game/07-game-fp/01-hacking/README.md
  projects/000-FIXME/xx-game/08-hacking/01-hacking/README.md
  projects/000-FIXME/xx-game/README.md
  projects/03-visitors/README.md
  projects/04-job-application/README.md
Labels: needs-review
