Repository Laboratoria/curriculum, pull requests merged in 2018-11, with the labels that each got.

#740 projects(cipher): adds checklist
  projects/01-cipher/README.md
Labels: enhancement, needs-review

#742 Fix in metadata
  topics/browser/02-dom/01-dom/README.md
Labels: bug

#737 translation(sprint7): general concepts
  99-general-concepts/01-debugging/00-opening/README.md
  99-general-concepts/01-debugging/01-intro/README.md
  99-general-concepts/01-debugging/02-error-messages/README.md
  99-general-concepts/01-debugging/03-code-challenges/01-say-hello/README.md
  99-general-concepts/01-debugging/03-code-challenges/01-say-hello/boilerplate/sayHello.js
  99-general-concepts/01-debugging/03-code-challenges/01-say-hello/solution/sayHello.js
  99-general-concepts/01-debugging/03-code-challenges/01-say-hello/test/sayHello.spec.js
  99-general-concepts/01-debugging/03-code-challenges/02-create-array/README.md
  99-general-concepts/01-debugging/03-code-challenges/02-create-array/boilerplate/createArray.js
  99-general-concepts/01-debugging/03-code-challenges/02-create-array/solution/createArray.js
  99-general-concepts/01-debugging/03-code-challenges/02-create-array/test/createArray.spec.js
  99-general-concepts/01-debugging/03-code-challenges/03-calculate-tip/README.md
  99-general-concepts/01-debugging/03-code-challenges/03-calculate-tip/boilerplate/calculateTip.js
  99-general-concepts/01-debugging/03-code-challenges/03-calculate-tip/solution/calculateTip.js
  99-general-concepts/01-debugging/03-code-challenges/03-calculate-tip/test/calculateTip.spec.js
  99-general-concepts/01-debugging/03-code-challenges/04-tell-fortune/README.md
  99-general-concepts/01-debugging/03-code-challenges/04-tell-fortune/boilerplate/tellFortune.js
  99-general-concepts/01-debugging/03-code-challenges/04-tell-fortune/solution/tellFortune.js
  99-general-concepts/01-debugging/03-code-challenges/04-tell-fortune/test/tellFortune.spec.js
  99-general-concepts/01-debugging/03-code-challenges/05-what-to-wear/README.md
  99-general-concepts/01-debugging/03-code-challenges/05-what-to-wear/boilerplate/whatToWear.js
  99-general-concepts/01-debugging/03-code-challenges/05-what-to-wear/solution/whatToWear.js
  99-general-concepts/01-debugging/03-code-challenges/05-what-to-wear/test/whatToWear.spec.js
  99-general-concepts/01-debugging/03-code-challenges/README.md
  99-general-concepts/01-debugging/04-breakpoints/README.md
  99-general-concepts/01-debugging/05-closing/README.md
  99-general-concepts/02-testing/00-opening/README.md
  99-general-concepts/02-testing/01-intro/README.md
  99-general-concepts/02-testing/02-unit-tests/README.md
  99-general-concepts/02-testing/03-closing/README.md
  99-general-concepts/03-style-guide/00-opening/README.md
  99-general-concepts/03-style-guide/01-style-guide/README.md
  99-general-concepts/03-style-guide/02-code-review/README.md
  99-general-concepts/03-style-guide/03-closing/README.md
  99-general-concepts/03-style-guide/03-linter/README.md
  99-general-concepts/03-style-guide/04-closing/README.md
  99-general-concepts/README.md
Labels: translation
