Repository Laboratoria/curriculum, pull requests merged in 2018-07, with the labels that each got.

#654 Fix misspell
  03-interactive-site/00-html-and-css/07-tipography-and-icons/README.md
  03-interactive-site/00-html-and-css/08-seminar/README.md
Labels: needs-review, translation

#656 content(projects/04-md-links): refactoring project for v2.x
  .mdlintignore
  projects/04-md-links/.editorconfig
  projects/04-md-links/.eslintrc
  projects/04-md-links/.gitignore
  projects/04-md-links/README.md
  projects/04-md-links/index.js
  projects/04-md-links/package.json
  projects/04-md-links/test/md-links.spec.js
Labels: content, needs-review

#657 Change LMS video to pt
  03-interactive-site/01-making-your-site-interactive/01-dom/README.md
  03-interactive-site/01-making-your-site-interactive/03-dom-manipulation/README.md
Labels: content, enhancement

#659 Portuguese videos for DOM, events and animation
  03-interactive-site/01-making-your-site-interactive/01-dom/README.md
  03-interactive-site/01-making-your-site-interactive/03-dom-manipulation/README.md
  03-interactive-site/01-making-your-site-interactive/04-events/README.md
Labels: content, needs-review, translation

#663 Translation chapter #1 and #2
  04-social-network/00-rwd/00-opening/README.md
  04-social-network/00-rwd/01-grid-system/README.md
  04-social-network/00-rwd/02-media-queries/README.md
  04-social-network/00-rwd/03-rwd/README.md
  04-social-network/00-rwd/04-quiz/README.md
  04-social-network/00-rwd/05-seminar/README.md
  04-social-network/00-rwd/06-guided-exercises/README.md
  04-social-network/00-rwd/07-code-challenges/README.md
  04-social-network/00-rwd/08-solutions-code-challenges/README.md
  04-social-network/00-rwd/09-requiz/README.md
  04-social-network/00-rwd/11-closing/README.md
  04-social-network/01-css-frameworks/00-opening/README.md
  04-social-network/01-css-frameworks/01-framework/README.md
  04-social-network/01-css-frameworks/02-bootstrap/README.md
  04-social-network/01-css-frameworks/03-materialize-and-more/README.md
  04-social-network/01-css-frameworks/04-components/README.md
  04-social-network/01-css-frameworks/05-quiz/README.md
  04-social-network/01-css-frameworks/06-seminar/README.md
  04-social-network/01-css-frameworks/07-guided-exercises/README.md
  04-social-network/01-css-frameworks/08-code-challenges/README.md
  04-social-network/01-css-frameworks/09-solutions/README.md
  04-social-network/01-css-frameworks/10-requiz/README.md
  04-social-network/01-css-frameworks/12-closing/README.md
  04-social-network/02-jquery/00-opening/README.md
  04-social-network/02-jquery/01-jQuery/README.md
  04-social-network/02-jquery/02-selectors/README.md
  04-social-network/02-jquery/03-dom/README.md
  04-social-network/02-jquery/04-events/README.md
  04-social-network/02-jquery/05-quiz/README.md
  04-social-network/02-jquery/06-seminar/README.md
  04-social-network/02-jquery/07-guided-exercises/README.md
  04-social-network/02-jquery/08-code-challenges/README.md
  04-social-network/02-jquery/09-solutions/README.md
  04-social-network/02-jquery/10-requiz/README.md
  04-social-network/02-jquery/12-closing/README.md
  04-social-network/03-design-process/00-opening/README.md
  04-social-network/03-design-process/01-prototyping/README.md
  04-social-network/03-design-process/02-seminar/README.md
  04-social-network/03-design-process/04-closing/README.md
  04-social-network/04-firebase-101/00-intro/README.md
  04-social-network/04-firebase-101/01-auth/README.md
  04-social-network/04-firebase-101/02-database/README.md
  04-social-network/05-social-network/01-final-product/README.md
  04-social-network/05-social-network/02-code-review/README.md
  04-social-network/05-social-network/03-solution/README.md
  04-social-network/05-social-network/05-retrospective/README.md
  04-social-network/README.md
Labels: content, translation

#665 translation(social-network): keeps consistency in part type for code challenges
  04-social-network/00-rwd/07-code-challenges/README.md
  04-social-network/01-css-frameworks/08-code-challenges/README.md
  04-social-network/02-jquery/08-code-challenges/README.md
  04-social-network/05-social-network/01-final-product/README.md
Labels: content, enhancement, translation

#666 Fix translation and change images
  04-social-network/00-rwd/02-media-queries/README.md
  04-social-network/00-rwd/02-media-queries/media_feature.png
  04-social-network/00-rwd/02-media-queries/media_type.png
  04-social-network/00-rwd/06-guided-exercises/README.md
  04-social-network/00-rwd/07-code-challenges/README.md
  04-social-network/00-rwd/10-self-assessment/README.md
  04-social-network/01-css-frameworks/03-materialize-and-more/README.md
  04-social-network/01-css-frameworks/11-self-assessment/README.md
  04-social-network/02-jquery/03-dom/README.md
  04-social-network/02-jquery/11-self-assessment/README.md
  04-social-network/03-design-process/03-self-assessment/README.md
  04-social-network/04-firebase-101/01-auth/README.md
  04-social-network/04-firebase-101/01-auth/side_menu.png
  04-social-network/05-social-network/04-survey/README.md
  04-social-network/README.md
Labels: content, enhancement, translation

#667 Restructure responsive web design lesson
  04-social-network/00-rwd/00-opening/README.md
  04-social-network/00-rwd/01-grid-system/README.md
  04-social-network/00-rwd/02-media-queries/README.md
  04-social-network/00-rwd/03-rwd/README.md
  04-social-network/00-rwd/04-quiz/README.md
  04-social-network/00-rwd/05-guided-exercises/README.md
  04-social-network/00-rwd/05-guided-exercises/ejercicio-grid-gral.png
  04-social-network/00-rwd/05-guided-exercises/ex-desktop-mobile.png
  04-social-network/00-rwd/05-guided-exercises/ex-desktop-mobile2.png
  04-social-network/00-rwd/05-guided-exercises/ex-desktop-mobile3.png
  04-social-network/00-rwd/05-guided-exercises/love-love-panda.png
  04-social-network/00-rwd/05-guided-exercises/rock-desktop.png
  04-social-network/00-rwd/05-guided-exercises/rock-movil.png
  04-social-network/00-rwd/05-seminar/README.md
  04-social-network/00-rwd/06-code-challenges/README.md
  04-social-network/00-rwd/06-code-challenges/desktop.png
  04-social-network/00-rwd/06-code-challenges/kitten-dawn.png
  04-social-network/00-rwd/06-code-challenges/kitten-night.png
  04-social-network/00-rwd/06-code-challenges/kitten-sunnyday.png
  04-social-network/00-rwd/06-code-challenges/responsive.png
  04-social-network/00-rwd/07-requiz/README.md
  04-social-network/00-rwd/08-closing/README.md
  04-social-network/00-rwd/08-solutions-code-challenges/README.md
  04-social-network/README.md
Labels: content, enhancement, translation

#673 Change article to portuguese
  04-social-network/00-rwd/01-grid-system/README.md
Labels: content, enhancement, translation
