Repository Laboratoria/curriculum, pull requests merged in 2018-12, with the labels that each got.

#734 fix content
  01-intro/01-introduction/04-quiz/README.md
Labels: enhancement

#749 Restructure folder for preadmission
  01-intro/01-introduction/00-welcome-and-orientation/README.md
  01-intro/01-introduction/01-growth-mindset/README.md
  01-intro/01-introduction/02-why-learn-to-code/README.md
  01-intro/01-introduction/03-your-first-website/README.md
  01-intro/02-content/01-html/README.md
  01-intro/02-content/02-css/README.md
  01-intro/02-content/03-css-display/README.md
  01-intro/02-content/04-values-data-types-and-operators/README.md
  01-intro/02-content/05-variables/README.md
  01-intro/02-content/06-self-learning-MDN/README.md
  01-intro/02-content/07-comments/README.md
  01-intro/02-content/08-conditionals-and-loops/README.md
  01-intro/02-content/09-practical-cases/README.md
  01-intro/02-content/10-functions/README.md
  01-intro/02-variables-and-data-types/04-guided-exercises/README.md
  01-intro/04-exercises/00-quiz-1/README.md
  01-intro/04-exercises/01-quiz-2/README.md
  01-intro/04-exercises/02-quiz-3/README.md
  01-intro/04-exercises/03-quiz-4/README.md
  01-intro/04-exercises/04-exercises/01-coin-convert/README.md
  01-intro/04-exercises/04-exercises/01-coin-convert/boilerplate/coinConvert.js
  01-intro/04-exercises/04-exercises/01-coin-convert/solution/coinConvert.js
  01-intro/04-exercises/04-exercises/01-coin-convert/test/coinConvert.spec.js
  01-intro/04-exercises/04-exercises/02-restaurant-bill/README.md
  01-intro/04-exercises/04-exercises/02-restaurant-bill/boilerplate/restaurantBill.js
  01-intro/04-exercises/04-exercises/02-restaurant-bill/solution/restaurantBill.js
  01-intro/04-exercises/04-exercises/02-restaurant-bill/test/restaurantBill.spec.js
  01-intro/04-exercises/04-exercises/README.md
  01-intro/04-flow-control/00-opening/README.md
  01-intro/04-flow-control/05-guided-exercises/README.md
  01-intro/04-flow-control/06-code-challenges/README.md
  01-intro/04-flow-control/08-closing/README.md
  01-intro/AGENDA.md
  01-intro/README.md
Labels: translation

#747 projects(dashboard): slowly re-writing project readme based on google doc
  projects/02-data-dashboard/README.md
  projects/02-data-dashboard/data/cohorts.json
  projects/02-data-dashboard/data/cohorts/lim-2018-03-pre-core-pw/progress.json
  projects/02-data-dashboard/data/cohorts/lim-2018-03-pre-core-pw/users.json
  projects/02-data-dashboard/package.json
  projects/02-data-dashboard/src/index.html
  projects/02-data-dashboard/src/style.css
  projects/02-data-dashboard/test/data.spec.js
  projects/02-data-dashboard/test/fixtures.js
  projects/02-data-dashboard/test/headless.js
  projects/02-data-dashboard/test/index.html
  projects/02-data-lovers/.editorconfig
  projects/02-data-lovers/.eslintignore
  projects/02-data-lovers/.eslintrc
  projects/02-data-lovers/.gitignore
  projects/02-data-lovers/README.md
  projects/02-data-lovers/package.json
  projects/02-data-lovers/src/data.js
  projects/02-data-lovers/src/data/injuries/injuries.js
  projects/02-data-lovers/src/data/injuries/injuries.json
  projects/02-data-lovers/src/data/lol/lol.js
  projects/02-data-lovers/src/data/lol/lol.json
  projects/02-data-lovers/src/data/pokemon/pokemon.js
  projects/02-data-lovers/src/data/pokemon/pokemon.json
  projects/02-data-lovers/src/data/steam/steam.js
  projects/02-data-lovers/src/data/steam/steam.json
  projects/02-data-lovers/src/data/worldbank/worldbank.js
  projects/02-data-lovers/src/data/worldbank/worldbank.json
  projects/02-data-lovers/src/index.html
  projects/02-data-lovers/src/main.js
  projects/02-data-lovers/src/style.css
  projects/02-data-lovers/test/.eslintrc
  projects/02-data-lovers/test/data.spec.js
Labels: content, in progress, needs-review

#758 Hide exercises for preadmission
  01-intro/README.md
Labels: chore

#759 Fixing broken links from World bank data description and some typos
  projects/02-data-lovers/README.md
  topics/shell/02-filesystem/01-fs/README.md
Labels: content, needs-review
