Repository Laboratoria/curriculum, pull requests merged in 2018-08, with the labels that each got.

#676 Grammar and spelling revision
  04-social-network/00-rwd/00-opening/README.md
  04-social-network/00-rwd/01-grid-system/README.md
  04-social-network/00-rwd/02-media-queries/README.md
  04-social-network/00-rwd/03-rwd/README.md
  04-social-network/00-rwd/04-quiz/README.md
  04-social-network/00-rwd/05-guided-exercises/README.md
  04-social-network/00-rwd/05-seminar/README.md
  04-social-network/00-rwd/07-requiz/README.md
  04-social-network/00-rwd/08-closing/README.md
  04-social-network/00-rwd/08-solutions-code-challenges/README.md
  04-social-network/01-css-frameworks/00-opening/README.md
  04-social-network/01-css-frameworks/01-framework/README.md
  04-social-network/01-css-frameworks/02-bootstrap/README.md
  04-social-network/01-css-frameworks/03-materialize-and-more/README.md
  04-social-network/01-css-frameworks/04-components/README.md
  04-social-network/01-css-frameworks/05-quiz/README.md
  04-social-network/01-css-frameworks/06-seminar/README.md
  04-social-network/01-css-frameworks/07-guided-exercises/README.md
  04-social-network/01-css-frameworks/08-code-challenges/README.md
  04-social-network/01-css-frameworks/09-solutions/README.md
  04-social-network/01-css-frameworks/10-requiz/README.md
  04-social-network/01-css-frameworks/12-closing/README.md
  04-social-network/02-jquery/00-opening/README.md
  04-social-network/02-jquery/01-jQuery/README.md
  04-social-network/02-jquery/03-dom/README.md
  04-social-network/02-jquery/04-events/README.md
  04-social-network/02-jquery/05-quiz/README.md
  04-social-network/02-jquery/06-seminar/README.md
  04-social-network/02-jquery/07-guided-exercises/README.md
  04-social-network/02-jquery/08-code-challenges/README.md
  04-social-network/02-jquery/09-solutions/README.md
  04-social-network/02-jquery/10-requiz/README.md
  04-social-network/03-design-process/00-opening/README.md
  04-social-network/03-design-process/01-prototyping/README.md
  04-social-network/03-design-process/02-seminar/README.md
  04-social-network/03-design-process/04-closing/README.md
  04-social-network/04-firebase-101/01-auth/README.md
  04-social-network/04-firebase-101/02-database/README.md
  04-social-network/05-social-network/01-final-product/README.md
  04-social-network/05-social-network/02-code-review/README.md
  04-social-network/05-social-network/03-solution/README.md
  04-social-network/05-social-network/04-survey/README.md
  04-social-network/05-social-network/05-retrospective/README.md
  04-social-network/README.md
Labels: content, enhancement, translation

#655 Errores en los tests identificados por las alumnas
  projects/02-data-dashboard/README.md
  projects/02-data-dashboard/test/data.spec.js
Labels: bug, needs-review

#677 V2.x
  .gitignore
  package.json
  projects/02-data-dashboard/README.md
  projects/02-data-dashboard/test/data.spec.js
  projects/03-social-network/README.md
  projects/031-registro-visitantes/README.md
  topics/javascript/01-basics/06-exercises/01-coin-convert/solution/coinConvert.js
  topics/javascript/04-arrays/06-practice/15-calculate-bill-total/solution/calculateBillTotal.js
  topics/javascript/05-objects/01-objects/index.js
  topics/javascript/05-objects/06-practice/02-remove-string-values-longer-than/solution/removeStringValuesLongerThan.js
  topics/javascript/05-objects/06-practice/13-add-object-property/solution/addObjectProperty.js
  topics/javascript/06-strings/02-practice/01-currency-amount/solution/currencyAmount.js
  yarn.lock
Labels: chore

#652 Modificación de proyecto red social
  projects/03-social-network/README.md
Labels: content, enhancement, needs-review

#680 content(projects/04-md-links): agrega rúbrica de evaluación
  projects/04-md-links/README.md
Labels: content, needs-review

#681 content(projects/04-md-links): agrega texto de intro, links a objetiv…
  projects/04-md-links/README.md
Labels: content, needs-review

#683 content(projects/04-md-links): cambia formato de parejas a individual
  projects/04-md-links/README.md
Labels: content, needs-review

#684 content(projects/04-md-links): Incluye el contenido de los PR.
  projects/04-md-links/README.md
Labels: content, needs-review

#692 tradução PT
  06-spa/04-errors/00-opening/README.md
Labels: content, translation

#693 Translation PT
  06-spa/04-errors/01-strict-mode/README.md
Labels: content, translation

#694 Translation PT
  06-spa/04-errors/02-try-catch/README.md
Labels: content, translation

#695 Translation PT
  06-spa/04-errors/03-callbacks/README.md
Labels: content, translation

#696 Translation PT
  06-spa/04-errors/04-promises/README.md
Labels: content, translation

#697 Translation PT
  06-spa/04-errors/05-practice/README.md
Labels: content, translation

#698 Translation PT
  06-spa/04-errors/07-closing/README.md
Labels: content, translation

#685 content(projects/04-md-links): agrega más detalle a checklist de completitud
  projects/04-md-links/README.md
Labels: enhancement, idea, needs-review

#686 projects/md-links: agrega sugerencias de implementacion
  projects/04-md-links/README.md
Labels: content, needs-review

#700 content(projects/04-md-links): adds tip about making your NPM modules installable via GitHub
  projects/04-md-links/README.md
Labels: content, needs-review

#702 Draft de Rehacer red social usando framework
  projects/04-social-network-frameworks/README.md
Labels: needs-review

#703 translation(deep-dive): updates validate-string exercise [pt]
  05-deep-dive/04-errors/05-practice/01-validate-string/README.md
Labels: content, translation

#704 translation(deep-dive): updates parse-json exercise
  05-deep-dive/04-errors/05-practice/02-parse-json/README.md
Labels: content, translation

#707 Updated with an extra challenge
  05-deep-dive/07-challenge/01-challenges/README.md
Labels: content, enhancement, translation
