Repository Laboratoria/curriculum, pull requests merged in 2018-05, with the labels that each got.

#578 [pt] Sprint 01, 2 sections
  02-basic-programming/00-welcome/00-opening/README.md
  02-basic-programming/00-welcome/01-about-laboratoria/README.md
  02-basic-programming/00-welcome/02-sprint-demo/README.md
  02-basic-programming/00-welcome/03-learning-at-laboratoria/README.md
  02-basic-programming/00-welcome/04-sprint-1-kickoff/README.md
  02-basic-programming/01-shell+git/00-opening/README.md
  02-basic-programming/01-shell+git/01-command-line/README.md
  02-basic-programming/01-shell+git/02-git/README.md
  02-basic-programming/01-shell+git/03-quiz/README.md
  03-interactive-site/README.md
  SUMMARY.md
Labels: content

#580 Fix linter issues
  02-basic-programming/00-welcome/00-opening/README.md
  02-basic-programming/00-welcome/01-about-laboratoria/README.md
  02-basic-programming/00-welcome/02-sprint-demo/README.md
  02-basic-programming/00-welcome/03-learning-at-laboratoria/README.md
  02-basic-programming/00-welcome/04-sprint-1-kickoff/README.md
  02-basic-programming/01-shell+git/00-opening/README.md
  02-basic-programming/01-shell+git/01-command-line/README.md
  02-basic-programming/01-shell+git/02-git/README.md
  02-basic-programming/01-shell+git/03-quiz/README.md
  SUMMARY.md
Labels: needs-review, translation

#586 Cambio gramatical
  projects/01-cipher/README.md
Labels: enhancement

#584 V2.x
  projects/01-cipher/README.md
  projects/02-data-dashboard/README.md
Labels: content, needs-review

#597 Corrección evaluación soft skills
  projects/01-cipher/README.md
  projects/01-cipher/src/cipher.js
Labels: needs-review

#601 v2.x cambios sugeridos en topic css
  topics/css/01-css/00-opening/README.md
  topics/css/01-css/03-free-exercises/README.md
  topics/css/01-css/07-free-exercises/README.md
  topics/css/01-css/07-free-exercises/img-tipo.png
  topics/css/01-css/10-free-exercises/README.md
  topics/css/01-css/10-free-exercises/img-nuestras-coders.png
  topics/css/01-css/13-closing/README.md
  topics/css/02-responsive/05-free-exercises/README.md
  topics/css/02-responsive/05-free-exercises/ejercicio-grid-gral.png
  topics/css/02-responsive/05-free-exercises/ex-desktop-mobile.png
  topics/css/02-responsive/05-free-exercises/ex-desktop-mobile2.png
  topics/css/02-responsive/05-free-exercises/ex-desktop-mobile3.png
  topics/css/02-responsive/05-free-exercises/love-love-panda.png
  topics/css/02-responsive/05-free-exercises/rock-desktop.png
  topics/css/02-responsive/05-free-exercises/rock-movil.png
  topics/css/02-responsive/18-closing/README.md
  topics/css/03-frameworks/06-free-exercises/README.md
  topics/css/03-frameworks/06-free-exercises/template-bootstrap.png
  topics/css/03-frameworks/09-closing/README.md
Labels: content, enhancement, needs-review

#609 tradução Controle de Fluxos PT
  01-intro/04-flow-control/00-opening/README.md
Labels: content

#605 v1.x - Realiza migración de ejercicios de replit con la estructura de la rama
  01-intro/04-flow-control/06-code-challenges/01-power-of-two/README.md
  01-intro/04-flow-control/06-code-challenges/01-power-of-two/boilerplate/powerOfTwo.js
  01-intro/04-flow-control/06-code-challenges/01-power-of-two/solution/powerOftwo.js
  01-intro/04-flow-control/06-code-challenges/01-power-of-two/test/powerOfTwo.spec.js
  01-intro/04-flow-control/06-code-challenges/02-reverse/README.md
  01-intro/04-flow-control/06-code-challenges/02-reverse/boilerplate/reverse.js
  01-intro/04-flow-control/06-code-challenges/02-reverse/solution/reverse.js
  01-intro/04-flow-control/06-code-challenges/02-reverse/test/reverse.spec.js
  01-intro/04-flow-control/06-code-challenges/03-count-vowels/README.md
  01-intro/04-flow-control/06-code-challenges/03-count-vowels/boilerplate/countVowels.js
  01-intro/04-flow-control/06-code-challenges/03-count-vowels/solution/countVowels.js
  01-intro/04-flow-control/06-code-challenges/03-count-vowels/test/countVowels.spec.js
  01-intro/04-flow-control/06-code-challenges/04-even-or-odd/README.md
  01-intro/04-flow-control/06-code-challenges/04-even-or-odd/boilerplate/evenOrOdd.js
  01-intro/04-flow-control/06-code-challenges/04-even-or-odd/solution/evenOrOdd.js
  01-intro/04-flow-control/06-code-challenges/04-even-or-odd/test/evenOrOdd.spec.js
  01-intro/04-flow-control/06-code-challenges/05-max/README.md
  01-intro/04-flow-control/06-code-challenges/05-max/boilerplate/max.js
  01-intro/04-flow-control/06-code-challenges/05-max/solution/max.js
  01-intro/04-flow-control/06-code-challenges/05-max/test/max.spec.js
  01-intro/04-flow-control/06-code-challenges/06-is-prime/README.md
  01-intro/04-flow-control/06-code-challenges/06-is-prime/boilerplate/isPrime.js
  01-intro/04-flow-control/06-code-challenges/06-is-prime/solution/isPrime.js
  01-intro/04-flow-control/06-code-challenges/06-is-prime/test/isPrime.spec.js
  01-intro/04-flow-control/06-code-challenges/07-can-drive-and-vote/README.md
  01-intro/04-flow-control/06-code-challenges/07-can-drive-and-vote/boilerplate/canDriveAndVote.js
  01-intro/04-flow-control/06-code-challenges/07-can-drive-and-vote/solution/canDriveAndVote.js
  01-intro/04-flow-control/06-code-challenges/07-can-drive-and-vote/test/canDriveAndVote.spec.js
  01-intro/04-flow-control/06-code-challenges/08-are-odd/README.md
  01-intro/04-flow-control/06-code-challenges/08-are-odd/boilerplate/areOdd.js
  01-intro/04-flow-control/06-code-challenges/08-are-odd/solution/areOdd.js
  01-intro/04-flow-control/06-code-challenges/08-are-odd/test/areOdd.spec.js
  01-intro/04-flow-control/06-code-challenges/README.md
Labels: needs-review

#610 Tradução Team SP 20181 PT
  01-intro/04-flow-control/01-conditionals-and-loops/README.md
Labels: content, translation

#613 Tradução Team SP 20181
  01-intro/04-flow-control/03-functions/README.md
Labels: content, translation

#614 Tradução Team SP 20181
  01-intro/04-flow-control/04-quiz-1/README.md
Labels: content, translation

#615 Tradução Team SP 20181
  01-intro/04-flow-control/08-closing/README.md
Labels: content, translation

#616 Tradução Team SP 20181
  01-intro/04-flow-control/05-guided-exercises/README.md
Labels: content, translation

#619 minor typos fixes
  02-basic-programming/03-objects/06-quiz/README.md
Labels: enhancement, translation

#611 Modificaciones a proyecto de data-dashboard
  projects/02-data-dashboard/README.md
Labels: content, needs-review

#618 V2.x
  projects/02-data-dashboard/README.md
Labels: content

#582 agregando tests para proyecto cipher
  projects/01-cipher/README.md
  projects/01-cipher/test/cipher.spec.js
Labels: enhancement, needs-review

#621 Tradução team SP
  01-intro/04-flow-control/07-quiz-2/README.md
Labels: needs-review, translation

#623 V2.x
  projects/02-data-dashboard/README.md
Labels: content, needs-review

#624 V2.x
  projects/01-cipher/README.md
  projects/02-data-dashboard/README.md
Labels: content, needs-review
