Repository Laboratoria/curriculum, pull requests merged in 2018-06, with the labels that each got.

#622 V2.x -DOM
  topics/browser/02-dom/00-opening/README.md
  topics/browser/02-dom/01-dom-traversing/README.md
  topics/browser/02-dom/01-dom/README.md
  topics/browser/02-dom/02-dom-manipulation/README.md
  topics/browser/02-dom/03-1-dom-methods-selection/README.md
  topics/browser/02-dom/03-2-dom-methods-crud/README.md
  topics/browser/02-dom/03-3-dom-methods-crud-attributes/readme.md
  topics/browser/02-dom/03-4-dom-methods-animations/readme.md
  topics/browser/02-dom/03-5-reflow-browser/README.md
  topics/browser/02-dom/03-browser-reflow/README.md
  topics/browser/02-dom/03-dom-manipulation/README.md
  topics/browser/02-dom/04-events/02-events/README.md
Labels: content, needs-review

#620 [pt] Table translation
  02-basic-programming/01-shell+git/01-command-line/README.md
  02-basic-programming/01-shell+git/02-git/README.md
Labels: needs-review, translation

#631 Change spanish links to portuguese
  03-interactive-site/00-html-and-css/01-html/README.md
Labels: content, needs-review, translation

#633 [pt] Translate JavaScript files
  02-basic-programming/02-arrays/06-practice/01-compute-average-length-of-words/test/computeAverageLengthOfWords.spec.js
  02-basic-programming/02-arrays/06-practice/02-get-nth-element/test/getNthElement.spec.js
  02-basic-programming/02-arrays/06-practice/03-convert-double-space-to-single/test/convertDoubleSpaceToSingle.spec.js
  02-basic-programming/02-arrays/06-practice/04-are-valid-credentials/test/areValidCredentials.spec.js
  02-basic-programming/02-arrays/06-practice/05-find-pair-for-sum/test/findPairForSum.spec.js
  02-basic-programming/02-arrays/06-practice/06-filter-odd-elements/test/filterOddElements.spec.js
  02-basic-programming/02-arrays/06-practice/07-find-shortest-word-among-mixed-elements/test/findShortestWordAmongMixedElements.spec.js
  02-basic-programming/02-arrays/06-practice/08-find-smallest-number-among-mixed-elements/test/findSmallestNumberAmongMixedElements.spec.js
  02-basic-programming/02-arrays/06-practice/09-get-longest-word-of-mixed-elements/test/getLongestWordOfMixedElements.spec.js
  02-basic-programming/02-arrays/06-practice/10-get-largest-number-among-mixed-elements/test/getLargestNumberAmongMixedElements.spec.js
  02-basic-programming/02-arrays/06-practice/11-compute-sum-of-all-elements/test/computeSumOfAllElements.spec.js
  02-basic-programming/02-arrays/06-practice/12-compute-sum-between/test/computeSumBetween.spec.js
  02-basic-programming/02-arrays/06-practice/13-get-longest-of-three-words/test/getLongestOfThreeWords.spec.js
  02-basic-programming/02-arrays/06-practice/14-find-shortest-of-three-words/test/findShortestOfThreeWords.spec.js
  02-basic-programming/02-arrays/06-practice/15-calculate-bill-total/test/calculateBillTotal.spec.js
  02-basic-programming/02-arrays/06-practice/16-convert-score-to-grade/solution/convertScoreToGrade.js
  02-basic-programming/02-arrays/06-practice/16-convert-score-to-grade/test/convertScoreToGrade.spec.js
  02-basic-programming/03-objects/08-practice/01-add-array-property/test/addArrayProperty.spec.js
  02-basic-programming/03-objects/08-practice/02-remove-string-values-longer-than/test/removeStringValuesLongerThan.spec.js
  02-basic-programming/03-objects/08-practice/03-get-element-of-array-property/test/getElementOfArrayProperty.spec.js
  02-basic-programming/03-objects/08-practice/04-greet-customer/test/greetCustomer.spec.js
  02-basic-programming/03-objects/08-practice/05-transform-first-and-last/test/transformFirstAndLast.spec.js
  02-basic-programming/03-objects/08-practice/06-get-all-keys/test/getAllKeys.spec.js
  02-basic-programming/03-objects/08-practice/07-from-list-to-object/test/fromListToObject.spec.js
  02-basic-programming/03-objects/08-practice/09-transform-employee-data/test/transformEmployeeData.spec.js
  02-basic-programming/03-objects/08-practice/10-convert-object-to-list/test/convertObjectToList.spec.js
  02-basic-programming/03-objects/08-practice/12-get-product-of-all-elements-at-property/test/getProductOfAllElementsAtProperty.spec.js
  02-basic-programming/03-objects/08-practice/13-add-object-property/test/addObjectProperty.spec.js
  02-basic-programming/03-objects/08-practice/14-add-full-name-property/test/addFullNameProperty.spec.js
Labels: content, needs-review, translation

#626 v2.x - Actualiza los ejercicios de objetos a ES6
  topics/javascript/05-objects/06-practice/00-add-array-property/README.md
  topics/javascript/05-objects/06-practice/00-add-array-property/boilerplate/addArrayProperty.js
  topics/javascript/05-objects/06-practice/00-add-array-property/solution/addArrayProperty.js
  topics/javascript/05-objects/06-practice/00-add-array-property/test/addArrayProperty.spec.js
  topics/javascript/05-objects/06-practice/01-object-properties-counter/README.md
  topics/javascript/05-objects/06-practice/02-remove-string-values-longer-than/README.md
  topics/javascript/05-objects/06-practice/02-remove-string-values-longer-than/boilerplate/removeStringValuesLongerThan.js
  topics/javascript/05-objects/06-practice/02-remove-string-values-longer-than/solution/removeStringValuesLongerThan.js
  topics/javascript/05-objects/06-practice/03-get-element-of-array-property/README.md
  topics/javascript/05-objects/06-practice/03-get-element-of-array-property/boilerplate/getElementOfArrayProperty.js
  topics/javascript/05-objects/06-practice/03-get-element-of-array-property/solution/getElementOfArrayProperty.js
  topics/javascript/05-objects/06-practice/04-greet-customer/README.md
  topics/javascript/05-objects/06-practice/04-greet-customer/boilerplate/greetCustomer.js
  topics/javascript/05-objects/06-practice/04-greet-customer/solution/greetCustomer.js
  topics/javascript/05-objects/06-practice/05-transform-first-and-last/README.md
  topics/javascript/05-objects/06-practice/05-transform-first-and-last/boilerplate/transformFirstAndLast.js
  topics/javascript/05-objects/06-practice/05-transform-first-and-last/solution/transformFirstAndLast.js
  topics/javascript/05-objects/06-practice/06-get-all-keys/README.md
  topics/javascript/05-objects/06-practice/06-get-all-keys/boilerplate/getAllKeys.js
  topics/javascript/05-objects/06-practice/06-get-all-keys/solution/getAllKeys.js
  topics/javascript/05-objects/06-practice/07-from-list-to-object/README.md
  topics/javascript/05-objects/06-practice/07-from-list-to-object/boilerplate/fromListToObject.js
  topics/javascript/05-objects/06-practice/07-from-list-to-object/solution/fromListToObject.js
  topics/javascript/05-objects/06-practice/08-list-all-values/README.md
  topics/javascript/05-objects/06-practice/08-list-all-values/boilerplate/listAllValues.js
  topics/javascript/05-objects/06-practice/08-list-all-values/solution/listAllValues.js
  topics/javascript/05-objects/06-practice/09-transform-employee-data/README.md
  topics/javascript/05-objects/06-practice/09-transform-employee-data/boilerplate/transformEmployeeData.js
  topics/javascript/05-objects/06-practice/09-transform-employee-data/solution/transformEmployeeData.js
  topics/javascript/05-objects/06-practice/10-convert-object-to-list/README.md
  topics/javascript/05-objects/06-practice/10-convert-object-to-list/boilerplate/convertObjectToList.js
  topics/javascript/05-objects/06-practice/10-convert-object-to-list/solution/convertObjectToList.js
  topics/javascript/05-objects/06-practice/11-get-sum-of-all-elements-at-property/README.md
  topics/javascript/05-objects/06-practice/11-get-sum-of-all-elements-at-property/boilerplate/getSumOfAllElementsAtProperty.js
  topics/javascript/05-objects/06-practice/11-get-sum-of-all-elements-at-property/solution/getSumOfAllElementsAtProperty.js
  topics/javascript/05-objects/06-practice/12-get-product-of-all-elements-at-property/README.md
  topics/javascript/05-objects/06-practice/12-get-product-of-all-elements-at-property/boilerplate/getProductOfAllElementsAtProperty.js
  topics/javascript/05-objects/06-practice/12-get-product-of-all-elements-at-property/solution/getProductOfAllElementsAtProperty.js
  topics/javascript/05-objects/06-practice/13-add-object-property/README.md
  topics/javascript/05-objects/06-practice/13-add-object-property/boilerplate/addObjectProperty.js
  topics/javascript/05-objects/06-practice/13-add-object-property/solution/addObjectProperty.js
  topics/javascript/05-objects/06-practice/13-add-object-property/test/addObjectProperty.spec.js
  topics/javascript/05-objects/06-practice/14-add-full-name-property/README.md
  topics/javascript/05-objects/06-practice/14-add-full-name-property/boilerplate/addFullNameProperty.js
Labels: content, enhancement, needs-review

#625 v2.x - Actualiza los ejercicios de arreglos a ES6
  topics/javascript/04-arrays/06-practice/01-compute-average-length-of-words/README.md
  topics/javascript/04-arrays/06-practice/01-compute-average-length-of-words/boilerplate/computeAverageLengthOfWords.js
  topics/javascript/04-arrays/06-practice/01-compute-average-length-of-words/solution/computeAverageLengthOfWords.js
  topics/javascript/04-arrays/06-practice/02-get-nth-element/README.md
  topics/javascript/04-arrays/06-practice/02-get-nth-element/boilerplate/getNthElement.js
  topics/javascript/04-arrays/06-practice/02-get-nth-element/solution/getNthElement.js
  topics/javascript/04-arrays/06-practice/03-convert-double-space-to-single/README.md
  topics/javascript/04-arrays/06-practice/03-convert-double-space-to-single/boilerplate/convertDoubleSpaceToSingle.js
  topics/javascript/04-arrays/06-practice/03-convert-double-space-to-single/solution/convertDoubleSpaceToSingle.js
  topics/javascript/04-arrays/06-practice/04-are-valid-credentials/README.md
  topics/javascript/04-arrays/06-practice/04-are-valid-credentials/boilerplate/areValidCredentials.js
  topics/javascript/04-arrays/06-practice/04-are-valid-credentials/solution/areValidCredentials.js
  topics/javascript/04-arrays/06-practice/05-find-pair-for-sum/README.md
  topics/javascript/04-arrays/06-practice/05-find-pair-for-sum/boilerplate/findPairForSum.js
  topics/javascript/04-arrays/06-practice/05-find-pair-for-sum/solution/findPairForSum.js
  topics/javascript/04-arrays/06-practice/06-filter-odd-elements/README.md
  topics/javascript/04-arrays/06-practice/06-filter-odd-elements/boilerplate/filterOddElements.js
  topics/javascript/04-arrays/06-practice/06-filter-odd-elements/solution/filterOddElements.js
  topics/javascript/04-arrays/06-practice/07-find-shortest-word-among-mixed-elements/README.md
  topics/javascript/04-arrays/06-practice/07-find-shortest-word-among-mixed-elements/boilerplate/findShortestWordAmongMixedElements.js
  topics/javascript/04-arrays/06-practice/07-find-shortest-word-among-mixed-elements/solution/findShortestWordAmongMixedElements.js
  topics/javascript/04-arrays/06-practice/08-find-smallest-number-among-mixed-elements/README.md
  topics/javascript/04-arrays/06-practice/08-find-smallest-number-among-mixed-elements/boilerplate/findSmallestNumberAmongMixedElements.js
  topics/javascript/04-arrays/06-practice/08-find-smallest-number-among-mixed-elements/solution/findSmallestNumberAmongMixedElements.js
  topics/javascript/04-arrays/06-practice/09-get-longest-word-of-mixed-elements/README.md
  topics/javascript/04-arrays/06-practice/09-get-longest-word-of-mixed-elements/boilerplate/getLongestWordOfMixedElements.js
  topics/javascript/04-arrays/06-practice/09-get-longest-word-of-mixed-elements/solution/getLongestWordOfMixedElements.js
  topics/javascript/04-arrays/06-practice/10-get-largest-number-among-mixed-elements/README.md
  topics/javascript/04-arrays/06-practice/10-get-largest-number-among-mixed-elements/boilerplate/getLargestNumberAmongMixedElements.js
  topics/javascript/04-arrays/06-practice/10-get-largest-number-among-mixed-elements/solution/getLargestNumberAmongMixedElements.js
  topics/javascript/04-arrays/06-practice/11-compute-sum-of-all-elements/README.md
  topics/javascript/04-arrays/06-practice/11-compute-sum-of-all-elements/boilerplate/computeSumOfAllElements.js
  topics/javascript/04-arrays/06-practice/11-compute-sum-of-all-elements/solution/computeSumOfAllElements.js
  topics/javascript/04-arrays/06-practice/12-compute-sum-between/README.md
  topics/javascript/04-arrays/06-practice/12-compute-sum-between/boilerplate/computeSumBetween.js
  topics/javascript/04-arrays/06-practice/12-compute-sum-between/solution/computeSumBetween.js
  topics/javascript/04-arrays/06-practice/13-get-longest-of-three-words/README.md
  topics/javascript/04-arrays/06-practice/13-get-longest-of-three-words/boilerplate/getLongestOfThreeWords.js
  topics/javascript/04-arrays/06-practice/13-get-longest-of-three-words/solution/getLongestOfThreeWords.js
  topics/javascript/04-arrays/06-practice/14-find-shortest-of-three-words/README.md
  topics/javascript/04-arrays/06-practice/14-find-shortest-of-three-words/boilerplate/findShortestOfThreeWords.js
  topics/javascript/04-arrays/06-practice/14-find-shortest-of-three-words/solution/findShortestOfThreeWords.js
  topics/javascript/04-arrays/06-practice/15-calculate-bill-total/README.md
  topics/javascript/04-arrays/06-practice/15-calculate-bill-total/boilerplate/calculateBillTotal.js
  topics/javascript/04-arrays/06-practice/15-calculate-bill-total/solution/calculateBillTotal.js
  topics/javascript/04-arrays/06-practice/16-convert-score-to-grade/README.md
  topics/javascript/04-arrays/06-practice/16-convert-score-to-grade/boilerplate/convertScoreToGrade.js
  topics/javascript/04-arrays/06-practice/16-convert-score-to-grade/solution/convertScoreToGrade.js
Labels: content, enhancement

#617 Cambios menores Pros y contras del uso de APIs
  topics/browser/04-xhr/03-working-with-apis/01-third-party-apis/README.md
Labels: content

#628 Se agrega información sobre git colaborativo a README de reto de data dashboard
  projects/02-data-dashboard/README.md
Labels: enhancement, needs-review

#639 translation(interactive-site): fixes ux-design part
  01-intro/01-introduction/00-welcome-and-orientation/README.md
  01-intro/01-introduction/01-growth-mindset/README.md
  01-intro/01-introduction/02-why-learn-to-code/README.md
  01-intro/01-introduction/03-your-first-website/README.md
  01-intro/01-introduction/04-quiz/README.md
  01-intro/02-variables-and-data-types/00-values-data-types-and-operators/README.md
  01-intro/02-variables-and-data-types/01-variables/README.md
  01-intro/02-variables-and-data-types/02-self-learning-MDN/README.md
  01-intro/02-variables-and-data-types/03-comments/README.md
  01-intro/02-variables-and-data-types/04-guided-exercises/README.md
  01-intro/02-variables-and-data-types/05-quiz/README.md
  01-intro/02-variables-and-data-types/06-exercises/01-coin-convert/README.md
  01-intro/02-variables-and-data-types/06-exercises/01-coin-convert/boilerplate/coinConvert.js
  01-intro/02-variables-and-data-types/06-exercises/01-coin-convert/solution/coinConvert.js
  01-intro/02-variables-and-data-types/06-exercises/01-coin-convert/test/coinConvert.spec.js
  01-intro/02-variables-and-data-types/06-exercises/02-restaurant-bill/README.md
  01-intro/02-variables-and-data-types/06-exercises/02-restaurant-bill/boilerplate/restaurantBill.js
  01-intro/02-variables-and-data-types/06-exercises/02-restaurant-bill/solution/restaurantBill.js
  01-intro/02-variables-and-data-types/06-exercises/02-restaurant-bill/test/restaurantBill.spec.js
  01-intro/04-flow-control/01-conditionals-and-loops/README.md
  01-intro/README.md
  03-interactive-site/02-ux-design/02-ux-design/README.md
Labels: chore, needs-review, translation

#641 translation(interactive-site): fixes syllabus unnecessary row format
  03-interactive-site/README.md
Labels: chore, translation

#636 New repo readme proposal for v2.x
  README.en-GB.md
  README.md
  README.pt-BR.md
  topics/scm/02-github/01-github/README.md
Labels: chore, needs-review

#642 Add 04-flow-control to 01-intro Syllabus
  01-intro/README.md
Labels: chore, translation

#643 edición redacción y habilidades blandas
  projects/03-social-network/README.md
Labels: content, needs-review

#644 Fix videos and links in ux unit
  03-interactive-site/02-ux-design/01-el-equipo-de-desarrollo/README.md
  03-interactive-site/02-ux-design/03-ux-design-vs-ui-design/README.md
  03-interactive-site/02-ux-design/04-navegacion/README.md
  03-interactive-site/02-ux-design/07-seminar/README.md
  03-interactive-site/02-ux-design/09-ux-challenges/README.md
Labels: content, enhancement

#648 chore(projects/02-data-dashboard): adds completion checklist
  projects/02-data-dashboard/README.md
Labels: idea, needs-review

#650 Restructure unit and translate links
  03-interactive-site/00-html-and-css/02-css/README.md
  03-interactive-site/00-html-and-css/03-box-model-and-display/README.md
  03-interactive-site/00-html-and-css/06-positioning-and-floats/README.md
  03-interactive-site/00-html-and-css/07-tipography-and-icons/README.md
  03-interactive-site/00-html-and-css/08-seminar/README.md
  03-interactive-site/00-html-and-css/08-soft-skills-4/README.md
  03-interactive-site/00-html-and-css/09-guided-exercises/README.md
  03-interactive-site/00-html-and-css/09-guided-exercises/img-tipo.png
  03-interactive-site/00-html-and-css/10-practical-cases/README.md
  03-interactive-site/00-html-and-css/11-quiz/README.md
  03-interactive-site/00-html-and-css/11-quiz/positioning.png
  03-interactive-site/00-html-and-css/12-seminar/README.md
  03-interactive-site/00-html-and-css/13-guided-exercises/README.md
  03-interactive-site/00-html-and-css/13-guided-exercises/img-nuestras-coders.png
  03-interactive-site/00-html-and-css/14-code-challenges/README.md
  03-interactive-site/00-html-and-css/15-soft-skills-5/README.md
  03-interactive-site/00-html-and-css/15-solutions-code-challenges/README.md
  03-interactive-site/00-html-and-css/16-requiz/README.md
  03-interactive-site/00-html-and-css/18-closing/README.md
  03-interactive-site/02-ux-design/02-ux-design/README.md
  03-interactive-site/README.md
Labels: enhancement, translation

#649 chore(projects/03-social-network): adds completion checklist
  projects/03-social-network/README.md
Labels: idea, needs-review

#651 ajustes de wording y estructura
  projects/03-social-network/README.md
Labels: content, needs-review
