Repository Laboratoria/curriculum, pull requests merged in 2018-02, with the labels that each got.

#505 chore(content): borra partes de self-assessment en 02-basic-programming
  02-basic-programming/01-basic-programming/17-closing/README.md
  02-basic-programming/01-basic-programming/17-self-assessment/README.md
  02-basic-programming/02-final-products/06-retrospective/README.md
  02-basic-programming/02-final-products/06-survey/README.md
Labels: chore

#506 chore(content): borra partes de self-assessment en curso 03-interactive
  03-interactive-site/00-html-and-css/19-closing/README.md
  03-interactive-site/00-html-and-css/19-self-assessment/README.md
  03-interactive-site/01-making-your-site-interactive/15-closing/README.md
  03-interactive-site/01-making-your-site-interactive/15-self-assessment/README.md
  03-interactive-site/02-ux-design/12-closing/README.md
  03-interactive-site/02-ux-design/12-self-assessment/README.md
  03-interactive-site/03-data-dashboard/04-retrospective/README.md
  03-interactive-site/03-data-dashboard/04-survey/README.md
Labels: chore

#500 content(06-spa): agrega contenido de unidad 3 (async requests with js)
  06-spa/01-html-5/07-geolocation/README.md
  06-spa/01-html-5/08-geolocation-challenges/README.md
  06-spa/01-html-5/09-dnd/README.md
  06-spa/01-html-5/10-dnd-challenges/README.md
  06-spa/02-asynchronous-js-request/01-client-server/README.md
  06-spa/02-asynchronous-js-request/01-consumo-apis/README.md
  06-spa/02-asynchronous-js-request/02-ajax/README.md
  06-spa/02-asynchronous-js-request/03-apis/README.md
  06-spa/02-asynchronous-js-request/03-apis/ejemplos-apis.png
  06-spa/02-asynchronous-js-request/04-xhr/README.md
  06-spa/02-asynchronous-js-request/04-xhr/sintax_open.png
  06-spa/02-asynchronous-js-request/05-xhr-demo/README.md
  06-spa/02-asynchronous-js-request/05-xhr-demo/imagenes/add-news1.png
  06-spa/02-asynchronous-js-request/05-xhr-demo/imagenes/add-news2.png
  06-spa/02-asynchronous-js-request/05-xhr-demo/imagenes/add-news3.png
  06-spa/02-asynchronous-js-request/05-xhr-demo/imagenes/consola-data.png
  06-spa/02-asynchronous-js-request/05-xhr-demo/imagenes/consola-data2.png
  06-spa/02-asynchronous-js-request/05-xhr-demo/imagenes/form-addEvent.png
  06-spa/02-asynchronous-js-request/05-xhr-demo/imagenes/getnews.png
  06-spa/02-asynchronous-js-request/05-xhr-demo/imagenes/handle-error.png
  06-spa/02-asynchronous-js-request/05-xhr-demo/imagenes/index-inicial.png
  06-spa/02-asynchronous-js-request/05-xhr-demo/imagenes/pantalla-final.png
  06-spa/02-asynchronous-js-request/05-xhr-demo/imagenes/pantalla-inicial.png
  06-spa/02-asynchronous-js-request/05-xhr-demo/imagenes/traemos-elementos.png
  06-spa/02-asynchronous-js-request/06-xhr-quiz/README.md
  06-spa/02-asynchronous-js-request/07-xhr-challenges/README.md
  06-spa/02-asynchronous-js-request/07-xhr-challenges/muestra.png
  06-spa/02-asynchronous-js-request/08-xhr-recap/README.md
  06-spa/02-asynchronous-js-request/09-jq-ajax/README.md
  06-spa/02-asynchronous-js-request/10-jq-ajax-demo/README.md
  06-spa/02-asynchronous-js-request/11-jq-shorthand-methods/README.md
  06-spa/02-asynchronous-js-request/13-jq-ajax-quiz/README.md
  06-spa/02-asynchronous-js-request/14-jq-ajax-challenges/README.md
  06-spa/02-asynchronous-js-request/15-jq-ajax-recap/README.md
  06-spa/02-asynchronous-js-request/jq-source-code/README.md
  06-spa/03-APIs/00-opening/README.md
  06-spa/03-APIs/01-api-html5/README.md
  06-spa/03-APIs/02-api-terceros/README.md
  06-spa/03-APIs/03-consumo-apis/README.md
  06-spa/03-working-with-apis/01-api-terceros/README.md
  06-spa/03-working-with-apis/01-third-party-apis/README.md
  06-spa/03-working-with-apis/02-public-apis/README.md
  06-spa/03-working-with-apis/03-secured-apis/README.md
  06-spa/03-working-with-apis/04-token-based-apis/README.md
  06-spa/03-working-with-apis/05-oauth/README.md
  06-spa/03-working-with-apis/06-rest/README.md
  06-spa/03-working-with-apis/07-crud/README.md
  06-spa/03-working-with-apis/notes/README.md
Labels: content, help wanted, needs-review

#508 content(06-spa): agrega contenido sobre unidad 4 (working-with-apis)
  06-spa/03-working-with-apis/00-opening/README.md
  06-spa/03-working-with-apis/01-third-party-apis/README.md
  06-spa/03-working-with-apis/02-public-apis/README.md
  06-spa/03-working-with-apis/02-web-apis/README.md
  06-spa/03-working-with-apis/02-web-apis/web-apis.png
  06-spa/03-working-with-apis/03-rest/README.md
  06-spa/03-working-with-apis/03-secured-apis/README.md
  06-spa/03-working-with-apis/04-crud/README.md
  06-spa/03-working-with-apis/04-token-based-apis/README.md
  06-spa/03-working-with-apis/05-api-challenges/README.md
  06-spa/03-working-with-apis/05-oauth/README.md
  06-spa/03-working-with-apis/06-quiz/README.md
  06-spa/03-working-with-apis/06-rest/README.md
  06-spa/03-working-with-apis/07-crud/README.md
  06-spa/03-working-with-apis/notes/README.md
Labels: content, help wanted

#511 content(06-spa): Añade challenge 01, 02 y 03 de Mixing-Up
  06-spa/01-html-5/08-geolocation-challenges/README.md
  06-spa/02-asynchronous-js-request/09-jq-ajax/README.md
  06-spa/02-asynchronous-js-request/10-jq-ajax-demo/README.md
  06-spa/02-asynchronous-js-request/11-jq-shorthand-methods/README.md
  06-spa/02-asynchronous-js-request/13-jq-ajax-quiz/README.md
  06-spa/02-asynchronous-js-request/14-jq-ajax-challenges/README.md
  06-spa/02-asynchronous-js-request/15-jq-ajax-recap/README.md
  06-spa/04-mixing-up/01-challenge-1/README.md
  06-spa/04-mixing-up/02-challenge-2/README.md
  06-spa/04-mixing-up/03-challenge-3/README.md
Labels: content, feedback

#515 content(06-spa): agrega challenges 07, 08 y 09 de unidad 04-mixing-up
  06-spa/04-mixing-up/01-challenge-1/README.md
  06-spa/04-mixing-up/02-challenge-2/README.md
  06-spa/04-mixing-up/03-challenge-3/README.md
  06-spa/04-mixing-up/04-challenge-4/README.md
  06-spa/04-mixing-up/05-challenge-5/README.md
  06-spa/04-mixing-up/07-challenge-7/README.md
  06-spa/04-mixing-up/08-challenge-8/README.md
  06-spa/04-mixing-up/09-challenge-9/README.md
Labels: content

#522 React quiz unidad 02-babel-and-webpack
  11-react/02-babel-and-webpack/07-quiz/README.md
Labels: content, needs-review
