Repository Laboratoria/curriculum, pull requests merged in 2019-10, with the labels that each got.

#896 topic(javascript): Adds note before old videos
  topics/javascript/01-basics/04-guided-exercises/README.md
  topics/javascript/01-basics/04-guided-exercises/README.pt-BR.md
Labels: chore, content

#875 Propuesta de readme con objetivos de aprendizaje para md-links
  projects/04-md-links/README.md
Labels: content, enhancement, needs-review

#892 update(topics&projects): update reactjs links in favor of spanish official documentation
  projects/000-FIXME/05-final-product/02-build-your-own-spa/README.md
  projects/04-burger-queen/README.md
  projects/04-social-network-frameworks/README.md
  topics/react/05-oop/04-state-lift-up/README.md
  topics/react/README.md
  topics/redux/02-design-and-setup/01-design/README.md
Labels: content, enhancement

#882 project(burger-queen-api)
  projects/04-burger-queen-api/.eslintignore
  projects/04-burger-queen-api/.eslintrc
  projects/04-burger-queen-api/.gitignore
  projects/04-burger-queen-api/README-docs.md
  projects/04-burger-queen-api/README.md
  projects/04-burger-queen-api/config.js
  projects/04-burger-queen-api/controller/__tests__/.eslintrc
  projects/04-burger-queen-api/controller/__tests__/users.spec.js
  projects/04-burger-queen-api/controller/users.js
  projects/04-burger-queen-api/db-data/.gitignore
  projects/04-burger-queen-api/docker-compose.yml
  projects/04-burger-queen-api/e2e/.eslintrc
  projects/04-burger-queen-api/e2e/auth.spec.js
  projects/04-burger-queen-api/e2e/globalSetup.js
  projects/04-burger-queen-api/e2e/globalTeardown.js
  projects/04-burger-queen-api/e2e/jest.config.js
  projects/04-burger-queen-api/e2e/orders.spec.js
  projects/04-burger-queen-api/e2e/products.spec.js
  projects/04-burger-queen-api/e2e/users.spec.js
  projects/04-burger-queen-api/index.js
  projects/04-burger-queen-api/jsdoc.conf
  projects/04-burger-queen-api/middleware/auth.js
  projects/04-burger-queen-api/middleware/error.js
  projects/04-burger-queen-api/package-lock.json
  projects/04-burger-queen-api/package.json
  projects/04-burger-queen-api/routes/auth.js
  projects/04-burger-queen-api/routes/index.js
  projects/04-burger-queen-api/routes/orders.js
  projects/04-burger-queen-api/routes/products.js
  projects/04-burger-queen-api/routes/users.js
  projects/04-burger-queen-api/sample.secrets.env
Labels: content, needs-review

#883 Burger Queen API Client
  projects/04-burger-queen-api-client/README.md
Labels: content, needs-review
