Repository Laboratoria/curriculum, pull requests merged in 2019-11, with the labels that each got.

#899 project(social-network) Propuesta de Readme con objetivos de aprendizaje
  projects/03-social-network/README.md
Labels: needs review

#895 Propuesta de linter de estilos para social-network
  projects/03-social-network/package.json
  projects/03-social-network/stylelint.config.js
Labels: content, enhancement

#908 Translate note fix
  topics/javascript/01-basics/02-variables/README.pt-BR.md
Labels: translation
