Repository Laboratoria/curriculum, pull requests merged in 2019-01, with the labels that each got.

#768 project(data-lovers): agrega info de requerimientos 'extra' para la segunda parte del proyecto
  projects/02-data-lovers/EXTRA.md
Labels: content, needs-review

#775 arreglando errores en la data, algunas url de los splash no estaban funcionando
  projects/02-data-lovers/src/data/lol/lol.json
Labels: bug, enhancement

#784 project(data-lovers): cambia var por const en archivos de data
  projects/02-data-lovers/src/data/injuries/injuries.js
  projects/02-data-lovers/src/data/lol/lol.js
  projects/02-data-lovers/src/data/pokemon/pokemon.js
  projects/02-data-lovers/src/data/steam/steam.js
  projects/02-data-lovers/src/data/worldbank/worldbank.js
Labels: enhancement

#779 projects(cipher): Agrega pruebas unitarias.
  projects/01-cipher/test/cipher.spec.js
Labels: enhancement, needs-review

#778 Modificando Readme de proyecto social network
  projects/03-social-network/README.md
  social-networt'
Labels: content, enhancement, needs-review
