Repository Laboratoria/curriculum, pull requests merged in 2020-11, with the labels that each got.

#1019 Updates dependencies in all projects containing a package.json
  projects/01-card-validation/package.json
  projects/01-cipher/package.json
  projects/02-data-lovers/package.json
  projects/02-emergency-room/package.json
  projects/03-social-network/package.json
Labels: chore

#1021 Fix cipher decode test function
  projects/01-cipher/test/cipher.spec.js
Labels: bug, content

#1017 Removes cloud functions from boilerplate in Burger Queen project
  projects/04-burger-queen/README.md
  projects/04-burger-queen/firebase.json
  projects/04-burger-queen/functions/.eslintrc.json
  projects/04-burger-queen/functions/index.js
  projects/04-burger-queen/functions/package.json
Labels: content, enhancement, needs review
