Repository Laboratoria/curriculum, pull requests merged in 2021-07, with the labels that each got.

#1075 Agrega proyectos roman-numerals y roman-numerals-slack
  learning-objectives/data.yml
  learning-objectives/intl/es.yml
  learning-objectives/intl/pt.yml
  projects/05-roman-numerals-slack/README.md
  projects/05-roman-numerals-slack/project.yml
  projects/05-roman-numerals/.gitignore
  projects/05-roman-numerals/README.md
  projects/05-roman-numerals/bin/cli.js
  projects/05-roman-numerals/index.js
  projects/05-roman-numerals/index.spec.js
  projects/05-roman-numerals/package.json
  projects/05-roman-numerals/project.yml
Labels: content, in progress

#1080 add readme pt-BR memory match
  projects/02-memory-match/README.pt-BR.md
Labels: content, translation

#1084 project(data-lovers): update images of data set (ghibli) at data lovers project
  projects/02-data-lovers/src/data/ghibli/ghibli.js
  projects/02-data-lovers/src/data/ghibli/ghibli.json
Labels: bug
