Repository Laboratoria/curriculum, pull requests merged in 2021-03, with the labels that each got.

#1039 Tests faltantes en validator.spec.js
  projects/01-card-validation/test/validator.spec.js
Labels: content, enhancement

#1026 Cambios a Objetivos de Aprendizaje README social network
  projects/03-social-network/README.md
Labels: HIGH PRIORITY, content, enhancement, idea

#1046 fix translation issues #1044
  projects/02-data-lovers/README.pt-BR.md
  projects/02-data-lovers/src/data/ghibli/README.pt-BR.md
Labels: translation

#1047 MDLinks: Más pistas, énfasis y recomendaciones para achicar el problema
  projects/04-md-links/README.md
Labels: content, enhancement
