Repository Laboratoria/curriculum, pull requests merged in 2022-03, with the labels that each got.

#1154 Translation(add news oa)
  learning-objectives/intl/pt.yml
Labels: content, translation

#1150 Job Application: Nuevo README
  .mdlintrc
  projects/06-job-application/Activities.md
  projects/06-job-application/Mentoring.md
  projects/06-job-application/README.md
Labels: content

#1133 project(wordpress-plugin): PHPMyAdmin, PHPUnit y logs de apache
  projects/05-wordpress-plugin/.gitignore
  projects/05-wordpress-plugin/README.md
  projects/05-wordpress-plugin/docker-compose.yml
  projects/05-wordpress-plugin/logs/.keep
Labels: enhancement, content

#1165 fix(scripts): Add 'node' before scripts fixing windows use
  package.json
Labels: bug
