Repository Laboratoria/curriculum, pull requests merged in 2022-11, with the labels that each got.

#1252 doc: removed heroku and added glitch & elephantSql
  projects/04-burger-queen-api/README.md
Labels: enhancement, content

#1230 Fixes #1229 to add reference to commit in cohort
  scripts/create-cohort-project.js
Labels: enhancement

#1269 fix(scripts): Fix create-cohort-project script for projects without a…
  scripts/create-cohort-project.js
Labels: bug
