Repository Laboratoria/curriculum, pull requests merged in 2022-08, with the labels that each got.

#1206 chore(OA-translation): Normalize OA's titles between ES and PT translations
  learning-objectives/intl/es.yml
  learning-objectives/intl/pt.yml
Labels: chore, translation

#1204 Topics/ux: Nuevos proyectos de UX y cambio de OA.
  learning-objectives/data.yml
  learning-objectives/intl/es.yml
  learning-objectives/intl/pt.yml
  projects/00-hcd-intro/project.yml
  projects/01-design-and-usability/project.yml
  projects/01-ui-design/README.md
  projects/01-ui-design/project.yml
  projects/01-ui-design/thumb.png
  projects/01-user-research/README.md
  projects/01-user-research/project.yml
  projects/01-user-research/thumb.png
  projects/02-small-businesses/proyect.yml
  projects/03-industry-deep-dive/README.md
  projects/03-industry-deep-dive/project.yml
  projects/03-industry-deep-dive/thumb.png
  projects/03-ui-design/project.yml
  projects/03-ux-consultancy/README.md
  projects/03-ux-consultancy/project.yml
  projects/03-ux-consultancy/thumb.png
  projects/04-portfolio/README.md
  projects/04-portfolio/proyect.yml
  projects/04-portfolio/thumb.png
  projects/04-service-design/README.md
  projects/04-service-design/thumb.png
  scripts/build.js
  src/intl/es/index.js
Labels: enhancement, content, in progress

#1152 Add deployment instructions for cipher and card validation projects
  projects/01-card-validation/README.md
  projects/01-card-validation/README.pt-BR.md
  projects/01-cipher/README.md
  projects/01-cipher/README.pt-BR.md
Labels: idea

#1208 📄 docs: fix translation
  projects/02-data-lovers/README.pt-BR.md
Labels: content, translation

#1207 fix(content): Social Network con Frameworks: Actualizar proyecto con Objetivos de Aprendizaje estandarizados y revisión general del enunciado
  projects/05-social-network-fw/README.md
  projects/05-social-network-fw/project.yml
Labels: content

#1190 Agrega canal de Slack de proyecto cipher a README.md
  projects/01-card-validation/README.md
  projects/01-cipher/README.md
Labels: question, idea, content, in progress
