Repository Laboratoria/curriculum, pull requests merged in 2022-07, with the labels that each got.

#1184 Ci cd
  .github/workflows/main.yml
  .github/workflows/node.js.yml
  .github/workflows/pr-preview.yml
  CONTRIBUTING.md
  DEPLOYMENT.md
  package.json
  scripts/README.md
  scripts/deploy.js
Labels: enhancement

#1185 fix(ci-cd)
  .github/workflows/main.yml
Labels: bug

#1191 Job Application: correcciones feedback ultima iteracion
  projects/06-job-application/Activities.md
  projects/06-job-application/README.md
Labels: enhancement, content

#1192 chore(update-browserlist): Update canisue-lite package for BrowserList
  package-lock.json
Labels: chore, dependencies

#1187 chore(node version): Actualiza la versión de node del repo de currícu…
  package-lock.json
  package.json
  projects/01-card-validation/package.json
  projects/01-cipher/package.json
  projects/02-data-lovers/package.json
  projects/02-emergency-room/package.json
  projects/02-memory-match/package.json
  projects/03-social-network/package.json
  projects/04-burger-queen-api/package.json
  projects/04-md-links/package.json
  projects/05-chat-app/package.json
  projects/05-roman-numerals/package.json
Labels: enhancement
