Repository Laboratoria/curriculum, pull requests merged in 2023-03, with the labels that each got.

#1316 feat(Home): Agrega link condicional según idioma y entorno (staging v…
  src/components/Home/index.jsx
  src/intl/es.js
  src/intl/index.jsx
  src/intl/pt.js
Labels: enhancement

#1319 feat(hosting):agregamos redirect para los urls de topics, y sin trail…
  firebase.json
Labels: enhancement

#1321 feat(hosting): Agrega redirects de track js a web-dev
  firebase.json
Labels: enhancement

#1322 refactor(projects): Unreleased projects are no longer part of the mai…
  dist/projects.json
  dist/projects/battleship.json
  dist/projects/burger-queen-api-client.json
  dist/projects/burger-queen-api.json
  dist/projects/burger-queen.json
  dist/projects/card-validation.json
  dist/projects/chat-app.json
  dist/projects/cipher.json
  dist/projects/data-lovers.json
  dist/projects/design-and-usability.json
  dist/projects/design-detectives.json
  dist/projects/emergency-room.json
  dist/projects/fleet-management.json
  dist/projects/hcd-intro.json
  dist/projects/industry-deep-dive.json
  dist/projects/job-application.json
  dist/projects/md-links.json
  dist/projects/memory-match.json
  dist/projects/movie-challenge.json
  dist/projects/news-alerts.json
  dist/projects/notes.json
  dist/projects/open-project.json
  dist/projects/portfolio.json
  dist/projects/roman-numerals-slack.json
  dist/projects/roman-numerals.json
  dist/projects/small-businesses.json
  dist/projects/social-network-fw.json
  dist/projects/social-network.json
  dist/projects/tic-tac-toe-rn.json
  dist/projects/trivia.json
  dist/projects/ux-consultancy.json
  dist/projects/visitors.json
  dist/projects/wordpress-plugin.json
  dist/topics.json
  dist/topics/browser.json
  dist/topics/content-management.json
  dist/topics/css.json
  dist/topics/functional.json
  dist/topics/html.json
  dist/topics/interaction-design.json
  dist/topics/intro-ux.json
  dist/topics/javascript.json
  dist/topics/paradigms.json
  dist/topics/prototyping.json
  dist/topics/scm.json
  dist/topics/shell.json
  dist/topics/ux-research.json
  projects/03-visitors/README.md
  projects/03-visitors/recepcion.jpg
  projects/03-visitors/thumb.png
  projects/04-news-alerts/README.md
  projects/04-news-alerts/lobsters.png
  projects/04-news-alerts/news-alerts.jpg
  projects/04-news-alerts/thumb.png
  projects/05-battleship/README.md
  projects/05-battleship/thumb.png
  projects/05-tic-tac-toe-rn/README.md
  projects/05-tic-tac-toe-rn/thumb.png
Labels: content, chore

#1329 feat(Part): Importa Content desde laboratoria/react y elimina el componente Content
  src/components/Content/Content.css
  src/components/Content/index.jsx
  src/components/Content/index.spec.js
  src/components/Part/index.jsx
Labels: enhancement

#1331 feat(topics): Adds Aprender a Aprender as a web dev topic
  dist/topics.json
  dist/topics/learning-mindset.json
  src/components/Breadcrumbs/index.jsx
  src/components/Topic/index.jsx
  topics/learning-mindset/01-welcome-and-objectives/01-welcome-and-objectives/README.md
  topics/learning-mindset/01-welcome-and-objectives/02-learning-misunderstandings/README.md
  topics/learning-mindset/README.md
  topics/learning-mindset/thumb.png
Labels: enhancement, content

#1334 feat(public): Actualiza título en HTML y manifest.json
  public/index.html
  public/manifest.json
Labels: chore
