Repository Laboratoria/curriculum, pull requests merged in 2023-06, with the labels that each got.

#1404 feat(TopBar): Quita título de menu de idioma
  src/components/TopBar/index.jsx
Labels: enhancement

#1412 content(UX Project): Nuevo proyecto para preadmisión de UX `how-might-we`
  projects/00-hcd-intro/README.md
  projects/00-hcd-intro/project.yml
  projects/00-hcd-intro/thumb.png
  projects/00-how-might-we/.editorconfig
  projects/00-how-might-we/.gitignore
  projects/00-how-might-we/README.md
  projects/00-how-might-we/project.yml
  projects/00-how-might-we/thumb.png
Labels: enhancement, content, in progress

#1423 chore(exercise): Adds CoinConvert titles in ES and PT README files
  topics/javascript/01-basics/06-exercises/01-coin-convert/README.md
  topics/javascript/01-basics/06-exercises/01-coin-convert/README.pt.md
Labels: content, chore, translation
