Repository Laboratoria/curriculum, pull requests merged in 2023-07, with the labels that each got.

#1430 chore(project): Updates thumb.png file of project data-lovers
  projects/02-data-lovers/thumb.png
Labels: bug, chore

#1390 feat(titles): Adds document title change on navigation
  src/__mocks__/@laboratoria/react.js
  src/components/Home/index.jsx
  src/components/Part/index.jsx
  src/components/Project/index.jsx
  src/components/Topic/index.jsx
  src/components/Track/index.jsx
  src/intl/es.js
  src/intl/pt.js
Labels: enhancement, in progress, translation

#1420 chore(project): Cambia imagen utilizada en proyecto `md-links`
  projects/04-md-links/README.md
  projects/04-md-links/README.pt.md
  projects/04-md-links/thumb.png
Labels: content, chore

#1450 chore(project): Adds titles in ES and PT for text-analyzer project in the app
  src/intl/es.js
  src/intl/pt.js
Labels: content, chore, translation

#1441 feat(docs): cambios a deployment y contributing con next
  CONTRIBUTING.md
  DEPLOYMENT.md
Labels: content, chore

#1479 fix(project): Arregla el género utilizado para referirse a la usuaria en el proyecto text-analyzer
  projects/01-text-analyzer/README.md
Labels: content, chore

#1484 fix: learning objectives typescript syntax
  learning-objectives/data.yml
Labels: bug

#1470 chore(project): Redo changes to `burger-queen-api-client` README in ES and adds the corresponding changes in the PT README as well
  projects/04-burger-queen-api-client/README.md
  projects/04-burger-queen-api-client/README.pt.md
Labels: content, chore, in progress, translation

#1475 fix: agrega Resumen de Proyecto a Text Analyzer
  projects/01-text-analyzer/README.md
Labels: bug

#1375 Readme mdLinks con hitos
  projects/04-md-links/README.md
  projects/04-md-links/docs/01-milestone.md
  projects/04-md-links/docs/02-milestone.md
  projects/04-md-links/docs/03-milestone.md
  projects/04-md-links/docs/04-milestone.md
  projects/04-md-links/docs/05-milestone.md
Labels: enhancement, content

#1498 fix: oas parecido a bq api client fixes #1483
  projects/05-movie-challenge-fw/project.yml
Labels: bug
