Repository Laboratoria/curriculum, pull requests merged in 2023-01, with the labels that each got.

#1245 Usamos Vite en Social Network para manejar las dependencias/Firebase modules
  projects/03-social-network/.eslintrc.json
  projects/03-social-network/README.md
  projects/03-social-network/README.pt-BR.md
  projects/03-social-network/package.json
  projects/03-social-network/vite.config.js
Labels: enhancement

#1284 Fix/JA pt-BR version
  projects/06-job-application/Activities.pt-BR.md
  projects/06-job-application/README.pt-BR.md
Labels: content, translation

#1289 some improvements for cipher project
  projects/01-cipher/README.md
  projects/01-cipher/README.pt-BR.md
Labels: enhancement, idea, content

#1288 Some improvements for card validation project
  projects/01-card-validation/AlgoritmoLuhn.png
  projects/01-card-validation/README.md
  projects/01-card-validation/README.pt-BR.md
Labels: enhancement, idea, content
