Repository Laboratoria/curriculum, pull requests merged in 2023-12, with the labels that each got.

#1676 Ajustes readme 02-dataverse
  projects/02-dataverse/README.md
  projects/02-dataverse/README.pt.md
Labels: content

#1633 Dataverse Chat Readme en portugues
  projects/03-dataverse-chat/README.pt.md
Labels: translation

#1673 Especificación de tests sobre atributos data-testid dentro de pruebas e2e
  projects/01-text-analyzer/README.md
  projects/01-text-analyzer/README.pt.md
Labels: content

#1662 Fix translation text analyzer
  projects/01-text-analyzer/README.md
  projects/01-text-analyzer/README.pt.md
Labels: bug
