Repository Laboratoria/curriculum, pull requests merged in 2023-09, with the labels that each got.

#1553 chore(docs): Actualiza todas las referencias antiguas del repo Laboratoria/bootcamp a Laboratoria/curriculum
  CONTRIBUTING.md
  DEPLOYMENT.md
  README.md
  README.pt.md
  package.json
  projects/01-text-analyzer/README.md
  projects/01-text-analyzer/README.pt.md
  projects/04-burger-queen-api/burger-queen-api.yml
  projects/04-md-links/README.md
  projects/04-md-links/README.pt.md
  projects/04-md-links/docs/04-milestone.md
  projects/05-social-network-fw/README.md
  scripts/create-cohort-project.mjs
Labels: chore

#1556 fix: add titles and links for some oas typescript
  learning-objectives/data.yml
  learning-objectives/intl/es.yml
  learning-objectives/intl/pt.yml
Labels: bug

#1570 fix(Topics): Actualiza las URLs rotas de 'topics/'
  learning-objectives/intl/es.yml
  learning-objectives/intl/pt.yml
  src/components/Breadcrumbs/index.jsx
  src/components/Part/index.jsx
Labels: bug, idea

#1604 New project Dataverse - feat/dataverse part 1
  projects/02-dataverse/.babelrc
  projects/02-dataverse/.editorconfig
  projects/02-dataverse/.eslintignore
  projects/02-dataverse/.eslintrc
  projects/02-dataverse/.github/workflows/playwright.yml
  projects/02-dataverse/.gitignore
  projects/02-dataverse/README.md
  projects/02-dataverse/package.json
  projects/02-dataverse/playwright.config.js
  projects/02-dataverse/project.yml
  projects/02-dataverse/src/data/dataset.js
  projects/02-dataverse/src/dataFunctions.js
  projects/02-dataverse/src/index.html
  projects/02-dataverse/src/main.js
  projects/02-dataverse/src/style.css
  projects/02-dataverse/src/view.js
  projects/02-dataverse/test/.eslintrc
  projects/02-dataverse/test/data.js
  projects/02-dataverse/test/dataFunctions.spec.js
  projects/02-dataverse/tests-read-only/.eslintrc
  projects/02-dataverse/tests-read-only/e2e/app.spec.js
  projects/02-dataverse/tests-read-only/oa/oa-css.spec.js
  projects/02-dataverse/tests-read-only/oa/oa-html.spec.js
  projects/02-dataverse/tests-read-only/oa/oa-javascript.spec.js
  projects/02-dataverse/tests-read-only/oa/oa-prompting.spec.js
  projects/02-dataverse/tests-read-only/oa/oa-web-api.spec.js
  projects/02-dataverse/thumb.png
Labels: content
