Repository Laboratoria/curriculum, pull requests merged in 2024-02, with the labels that each got.

#1457 Primera version de FAQ para BQAC
  projects/04-burger-queen-api-client/README.md
  projects/04-burger-queen-api-client/README.pt.md
  projects/04-burger-queen-api-client/docs/FAQ.md
  projects/04-burger-queen-api-client/docs/FAQ.pt.md
Labels: content, in progress, translation

#1750 fix: links to guide router-spa and more explicit link text
  projects/03-dataverse-chat/docs/01-milestone.md
  projects/03-dataverse-chat/docs/03-milestone.md
Labels: bug

#1752 feat(deps): Actualiza dependencia @laboratoria/sdk-react
  __mocks__/@laboratoria/sdk-react.jsx
  package-lock.json
  package.json
  public/workers
  src/components/App/App.spec.jsx
  src/components/App/RoutesWithIntl.jsx
  src/components/App/index.jsx
  src/components/Home/index.jsx
  src/components/Part/index.jsx
  src/components/Project/index.jsx
  src/components/TopBar/DrawerMenu.jsx
  src/components/TopBar/index.jsx
  src/components/TopBar/index.spec.jsx
  src/components/Topic/index.jsx
  src/components/Track/Gym.jsx
  src/components/Track/Projects.jsx
  src/components/Track/Topics.jsx
  src/components/Track/index.jsx
  src/index.jsx
Labels: enhancement, chore, dependencies
